name: CWAG Build & Test Integration

on:
  workflow_dispatch: null
  push:
    branches:
      - master
      - 'v1.*'
      
jobs:
  docker-build:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-20.04
    steps:
      - name: Run docker compose
        run: |
          cd sample
          docker build -t my_image .
