name: CWAG Build & Test Integration

on:
  workflow_dispatch: null
  push:
    branches:
      - master
      - 'v1.*'
      
jobs:
  docker-build:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Add this step to ensure the repository is checked out

      - name: Run Docker Compose
        run: |
          ls  # List contents of the current directory for debugging purposes
          cd sample
          docker build -t my_image .
      - name: Export docker images to deploy them
        run: |
          mkdir images
          cd images
          docker save my_image:latest | gzip > my_image.tar.gz
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # pin@v3
        with:
          name: docker-images
          path: images
